services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: unless-stopped
    user: node
    command: pnpm dev

volumes:
  node_modules: {}
